CREATE DATABASE IF NOT EXISTS `jokes_maspero`;
USE `jokes_maspero`;

CREATE TABLE IF NOT EXISTS `users` (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(64) NOT NULL UNIQUE,
	`password_hash` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `jokes` (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`joke_text` TEXT NOT NULL,
	`author_id` INT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_joke_author` FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
);
